<Project>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <Authors>AITIS s.r.o.</Authors>
    <PackageProjectUrl>https://whales.exchange</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AnalysisLevel>latest</AnalysisLevel>
    <LangVersion>14.0</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsAotCompatible>false</IsAotCompatible>
    <PublishAot>false</PublishAot>

    <!-- https://github.com/dotnet/project-system/blob/436bc57cc69f41f7ad3bd6dd7cb5d2e433441d77/docs/build-acceleration.md -->
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
    <PackageReference Include="NLog" PrivateAssets="all" />
    <PackageReference Include="WhalesSecret.ScriptApiLib" />
  </ItemGroup>
</Project>